// <auto-generated />
using System;
using MVC_DOTNET_SALES.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_DOTNET_SALES.Migrations
{
    [DbContext(typeof(MVC_DOTNET_SALESContext))]
    [Migration("20210313045617_OutraMigracao")]
    partial class OutraMigracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MVC_DOTNET_SALES.Models.Departamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("MVC_DOTNET_SALES.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int>("Status");

                    b.Property<double>("Valor");

                    b.Property<int?>("VendedorId");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("ControleVendas");
                });

            modelBuilder.Entity("MVC_DOTNET_SALES.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Departamentoid");

                    b.Property<DateTime>("Dt_aniversario");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<double>("SalarioBase");

                    b.HasKey("Id");

                    b.HasIndex("Departamentoid");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("MVC_DOTNET_SALES.Models.SalesRecord", b =>
                {
                    b.HasOne("MVC_DOTNET_SALES.Models.Seller", "Vendedor")
                        .WithMany("Vendas")
                        .HasForeignKey("VendedorId");
                });

            modelBuilder.Entity("MVC_DOTNET_SALES.Models.Seller", b =>
                {
                    b.HasOne("MVC_DOTNET_SALES.Models.Departamento", "Departamento")
                        .WithMany("Vendedores")
                        .HasForeignKey("Departamentoid");
                });
#pragma warning restore 612, 618
        }
    }
}
